// 310+ stocks: NSE, NASDAQ, NYSE, CRYPTO
// Format: [symbol, yahoo, name, exchange, currency, sector]
const S = (s, y, n, e, c, sec) => ({
  symbol: s,
  yahoo: y,
  name: n,
  exchange: e,
  currency: c,
  sector: sec || 'Other',
})
export const STOCK_CONFIG = [
  // ═══ NSE STOCKS (92) ═══
  S('RELIANCE', 'RELIANCE.NS', 'Reliance Industries', 'NSE', 'INR', 'Energy'),
  S('TCS', 'TCS.NS', 'Tata Consultancy Services', 'NSE', 'INR', 'Technology'),
  S('HDFCBANK', 'HDFCBANK.NS', 'HDFC Bank', 'NSE', 'INR', 'Finance'),
  S('INFY', 'INFY.NS', 'Infosys', 'NSE', 'INR', 'Technology'),
  S('ICICIBANK', 'ICICIBANK.NS', 'ICICI Bank', 'NSE', 'INR', 'Finance'),
  S('KOTAKBANK', 'KOTAKBANK.NS', 'Kotak Mahindra Bank', 'NSE', 'INR', 'Finance'),
  S('HINDUNILVR', 'HINDUNILVR.NS', 'Hindustan Unilever', 'NSE', 'INR', 'Consumer'),
  S('ITC', 'ITC.NS', 'ITC Limited', 'NSE', 'INR', 'Consumer'),
  S('SBIN', 'SBIN.NS', 'State Bank of India', 'NSE', 'INR', 'Finance'),
  S('BAJFINANCE', 'BAJFINANCE.NS', 'Bajaj Finance', 'NSE', 'INR', 'Finance'),
  S('BHARTIARTL', 'BHARTIARTL.NS', 'Bharti Airtel', 'NSE', 'INR', 'Technology'),
  S('ASIANPAINT', 'ASIANPAINT.NS', 'Asian Paints', 'NSE', 'INR', 'Materials'),
  S('MARUTI', 'MARUTI.NS', 'Maruti Suzuki', 'NSE', 'INR', 'Consumer'),
  S('TITAN', 'TITAN.NS', 'Titan Company', 'NSE', 'INR', 'Consumer'),
  S('AXISBANK', 'AXISBANK.NS', 'Axis Bank', 'NSE', 'INR', 'Finance'),
  S('WIPRO', 'WIPRO.NS', 'Wipro', 'NSE', 'INR', 'Technology'),
  S('ULTRACEMCO', 'ULTRACEMCO.NS', 'UltraTech Cement', 'NSE', 'INR', 'Materials'),
  S('NESTLEIND', 'NESTLEIND.NS', 'Nestle India', 'NSE', 'INR', 'Consumer'),
  S('POWERGRID', 'POWERGRID.NS', 'Power Grid Corp', 'NSE', 'INR', 'Energy'),
  S('NTPC', 'NTPC.NS', 'NTPC Limited', 'NSE', 'INR', 'Energy'),
  S('ONGC', 'ONGC.NS', 'Oil & Natural Gas Corp', 'NSE', 'INR', 'Energy'),
  S('SUNPHARMA', 'SUNPHARMA.NS', 'Sun Pharmaceutical', 'NSE', 'INR', 'Healthcare'),
  S('TATAMOTORS', 'TATAMT.NS', 'Tata Motors', 'NSE', 'INR', 'Consumer'),
  S('HCLTECH', 'HCLTECH.NS', 'HCL Technologies', 'NSE', 'INR', 'Technology'),
  S('TATASTEEL', 'TATASTEEL.NS', 'Tata Steel', 'NSE', 'INR', 'Materials'),
  S('COALINDIA', 'COALINDIA.NS', 'Coal India', 'NSE', 'INR', 'Energy'),
  S('DIVISLAB', 'DIVISLAB.NS', "Divi's Laboratories", 'NSE', 'INR', 'Healthcare'),
  S('CIPLA', 'CIPLA.NS', 'Cipla Limited', 'NSE', 'INR', 'Healthcare'),
  S('ADANIENT', 'ADANIENT.NS', 'Adani Enterprises', 'NSE', 'INR', 'Industrial'),
  S('ADANIPORTS', 'ADANIPORTS.NS', 'Adani Ports', 'NSE', 'INR', 'Industrial'),
  S('BAJAJ-AUTO', 'BAJAJ-AUTO.NS', 'Bajaj Auto', 'NSE', 'INR', 'Consumer'),
  S('BAJAJFINSV', 'BAJAJFINSV.NS', 'Bajaj Finserv', 'NSE', 'INR', 'Finance'),
  S('BPCL', 'BPCL.NS', 'Bharat Petroleum', 'NSE', 'INR', 'Energy'),
  S('BRITANNIA', 'BRITANNIA.NS', 'Britannia Industries', 'NSE', 'INR', 'Consumer'),
  S('DRREDDY', 'DRREDDY.NS', 'Dr. Reddys Laboratories', 'NSE', 'INR', 'Healthcare'),
  S('EICHERMOT', 'EICHERMOT.NS', 'Eicher Motors', 'NSE', 'INR', 'Consumer'),
  S('GRASIM', 'GRASIM.NS', 'Grasim Industries', 'NSE', 'INR', 'Materials'),
  S('HDFCLIFE', 'HDFCLIFE.NS', 'HDFC Life Insurance', 'NSE', 'INR', 'Finance'),
  S('HEROMOTOCO', 'HEROMOTOCO.NS', 'Hero MotoCorp', 'NSE', 'INR', 'Consumer'),
  S('HINDALCO', 'HINDALCO.NS', 'Hindalco Industries', 'NSE', 'INR', 'Materials'),
  S('INDUSINDBK', 'INDUSINDBK.NS', 'IndusInd Bank', 'NSE', 'INR', 'Finance'),
  S('JSWSTEEL', 'JSWSTEEL.NS', 'JSW Steel', 'NSE', 'INR', 'Materials'),
  S('LT', 'LT.NS', 'Larsen & Toubro', 'NSE', 'INR', 'Industrial'),
  S('M&M', 'M%26M.NS', 'Mahindra & Mahindra', 'NSE', 'INR', 'Consumer'),
  S('SBILIFE', 'SBILIFE.NS', 'SBI Life Insurance', 'NSE', 'INR', 'Finance'),
  S('SHREECEM', 'SHREECEM.NS', 'Shree Cement', 'NSE', 'INR', 'Materials'),
  S('TECHM', 'TECHM.NS', 'Tech Mahindra', 'NSE', 'INR', 'Technology'),
  S('TATACONSUM', 'TATACONSUM.NS', 'Tata Consumer Products', 'NSE', 'INR', 'Consumer'),
  S('UPL', 'UPL.NS', 'UPL Limited', 'NSE', 'INR', 'Materials'),
  S('VEDL', 'VEDL.NS', 'Vedanta Limited', 'NSE', 'INR', 'Materials'),
  // NIFTY NEXT 50
  S('ADANIGREEN', 'ADANIGREEN.NS', 'Adani Green Energy', 'NSE', 'INR', 'Energy'),
  S('AMBUJACEM', 'AMBUJACEM.NS', 'Ambuja Cements', 'NSE', 'INR', 'Materials'),
  S('BANKBARODA', 'BANKBARODA.NS', 'Bank of Baroda', 'NSE', 'INR', 'Finance'),
  S('BERGEPAINT', 'BERGEPAINT.NS', 'Berger Paints', 'NSE', 'INR', 'Materials'),
  S('BIOCON', 'BIOCON.NS', 'Biocon Limited', 'NSE', 'INR', 'Healthcare'),
  S('BOSCHLTD', 'BOSCHLTD.NS', 'Bosch Limited', 'NSE', 'INR', 'Industrial'),
  S('CANBK', 'CANBK.NS', 'Canara Bank', 'NSE', 'INR', 'Finance'),
  S('COLPAL', 'COLPAL.NS', 'Colgate-Palmolive India', 'NSE', 'INR', 'Consumer'),
  S('DABUR', 'DABUR.NS', 'Dabur India', 'NSE', 'INR', 'Consumer'),
  S('DMART', 'DMART.NS', 'Avenue Supermarts', 'NSE', 'INR', 'Consumer'),
  S('GAIL', 'GAIL.NS', 'GAIL India', 'NSE', 'INR', 'Energy'),
  S('GODREJCP', 'GODREJCP.NS', 'Godrej Consumer Products', 'NSE', 'INR', 'Consumer'),
  S('HAVELLS', 'HAVELLS.NS', 'Havells India', 'NSE', 'INR', 'Industrial'),
  S('ICICIGI', 'ICICIGI.NS', 'ICICI Lombard General', 'NSE', 'INR', 'Finance'),
  S('INDIGO', 'INDIGO.NS', 'InterGlobe Aviation', 'NSE', 'INR', 'Industrial'),
  S('LUPIN', 'LUPIN.NS', 'Lupin Limited', 'NSE', 'INR', 'Healthcare'),
  S('MARICO', 'MARICO.NS', 'Marico Limited', 'NSE', 'INR', 'Consumer'),
  S('MCDOWELL-N', 'UNITDSPR.NS', 'United Spirits', 'NSE', 'INR', 'Consumer'),
  S('MUTHOOTFIN', 'MUTHOOTFIN.NS', 'Muthoot Finance', 'NSE', 'INR', 'Finance'),
  S('NAUKRI', 'NAUKRI.NS', 'Info Edge India', 'NSE', 'INR', 'Technology'),
  S('POONAWALLA', 'POONAWALLA.NS', 'Poonawalla Fincorp', 'NSE', 'INR', 'Finance'),
  S('PIDILITIND', 'PIDILITIND.NS', 'Pidilite Industries', 'NSE', 'INR', 'Materials'),
  S('PIIND', 'PIIND.NS', 'PI Industries', 'NSE', 'INR', 'Materials'),
  S('PNB', 'PNB.NS', 'Punjab National Bank', 'NSE', 'INR', 'Finance'),
  S('RECLTD', 'RECLTD.NS', 'REC Limited', 'NSE', 'INR', 'Finance'),
  S('SIEMENS', 'SIEMENS.NS', 'Siemens India', 'NSE', 'INR', 'Industrial'),
  S('SRF', 'SRF.NS', 'SRF Limited', 'NSE', 'INR', 'Materials'),
  S('TORNTPHARM', 'TORNTPHARM.NS', 'Torrent Pharma', 'NSE', 'INR', 'Healthcare'),
  S('TRENT', 'TRENT.NS', 'Trent Limited', 'NSE', 'INR', 'Consumer'),
  S('VBL', 'VBL.NS', 'Varun Beverages', 'NSE', 'INR', 'Consumer'),
  S('VOLTAS', 'VOLTAS.NS', 'Voltas Limited', 'NSE', 'INR', 'Consumer'),
  S('ZYDUSLIFE', 'ZYDUSLIFE.NS', 'Zydus Lifesciences', 'NSE', 'INR', 'Healthcare'),
  // Mid/Small Cap
  S('IRFC', 'IRFC.NS', 'Indian Railway Finance', 'NSE', 'INR', 'Finance'),
  S('SUZLON', 'SUZLON.NS', 'Suzlon Energy', 'NSE', 'INR', 'Energy'),
  S('YESBANK', 'YESBANK.NS', 'Yes Bank', 'NSE', 'INR', 'Finance'),
  S('IRCTC', 'IRCTC.NS', 'IRCTC', 'NSE', 'INR', 'Industrial'),
  S('ZOMATO', 'ETERNAL.NS', 'Zomato (Eternal)', 'NSE', 'INR', 'Technology'),
  S('NYKAA', 'NYKAA.NS', 'FSN E-Commerce (Nykaa)', 'NSE', 'INR', 'Consumer'),
  S('PAYTM', 'PAYTM.NS', 'One97 Communications', 'NSE', 'INR', 'Technology'),
  S('POLICYBZR', 'POLICYBZR.NS', 'PB Fintech', 'NSE', 'INR', 'Finance'),
  S('DELHIVERY', 'DELHIVERY.NS', 'Delhivery', 'NSE', 'INR', 'Industrial'),
  // ═══ NASDAQ (100) ═══
  S('AAPL', 'AAPL', 'Apple Inc', 'NASDAQ', 'USD', 'Technology'),
  S('MSFT', 'MSFT', 'Microsoft Corp', 'NASDAQ', 'USD', 'Technology'),
  S('GOOGL', 'GOOGL', 'Alphabet Inc', 'NASDAQ', 'USD', 'Technology'),
  S('GOOG', 'GOOG', 'Alphabet Inc Class C', 'NASDAQ', 'USD', 'Technology'),
  S('AMZN', 'AMZN', 'Amazon.com Inc', 'NASDAQ', 'USD', 'Technology'),
  S('NVDA', 'NVDA', 'NVIDIA Corp', 'NASDAQ', 'USD', 'Technology'),
  S('META', 'META', 'Meta Platforms', 'NASDAQ', 'USD', 'Technology'),
  S('TSLA', 'TSLA', 'Tesla Inc', 'NASDAQ', 'USD', 'Consumer'),
  S('AVGO', 'AVGO', 'Broadcom Inc', 'NASDAQ', 'USD', 'Technology'),
  S('COST', 'COST', 'Costco Wholesale', 'NASDAQ', 'USD', 'Consumer'),
  S('NFLX', 'NFLX', 'Netflix Inc', 'NASDAQ', 'USD', 'Consumer'),
  S('AMD', 'AMD', 'Advanced Micro Devices', 'NASDAQ', 'USD', 'Technology'),
  S('INTC', 'INTC', 'Intel Corporation', 'NASDAQ', 'USD', 'Technology'),
  S('QCOM', 'QCOM', 'Qualcomm Inc', 'NASDAQ', 'USD', 'Technology'),
  S('TXN', 'TXN', 'Texas Instruments', 'NASDAQ', 'USD', 'Technology'),
  S('MU', 'MU', 'Micron Technology', 'NASDAQ', 'USD', 'Technology'),
  S('AMAT', 'AMAT', 'Applied Materials', 'NASDAQ', 'USD', 'Technology'),
  S('LRCX', 'LRCX', 'Lam Research', 'NASDAQ', 'USD', 'Technology'),
  S('KLAC', 'KLAC', 'KLA Corporation', 'NASDAQ', 'USD', 'Technology'),
  S('MRVL', 'MRVL', 'Marvell Technology', 'NASDAQ', 'USD', 'Technology'),
  S('ADBE', 'ADBE', 'Adobe Inc', 'NASDAQ', 'USD', 'Technology'),
  S('CRM', 'CRM', 'Salesforce Inc', 'NASDAQ', 'USD', 'Technology'),
  S('ORCL', 'ORCL', 'Oracle Corporation', 'NASDAQ', 'USD', 'Technology'),
  S('CSCO', 'CSCO', 'Cisco Systems', 'NASDAQ', 'USD', 'Technology'),
  S('PYPL', 'PYPL', 'PayPal Holdings', 'NASDAQ', 'USD', 'Finance'),
  S('INTU', 'INTU', 'Intuit Inc', 'NASDAQ', 'USD', 'Technology'),
  S('SNPS', 'SNPS', 'Synopsys Inc', 'NASDAQ', 'USD', 'Technology'),
  S('CDNS', 'CDNS', 'Cadence Design Systems', 'NASDAQ', 'USD', 'Technology'),
  S('FTNT', 'FTNT', 'Fortinet Inc', 'NASDAQ', 'USD', 'Technology'),
  S('PANW', 'PANW', 'Palo Alto Networks', 'NASDAQ', 'USD', 'Technology'),
  S('CRWD', 'CRWD', 'CrowdStrike Holdings', 'NASDAQ', 'USD', 'Technology'),
  S('ZS', 'ZS', 'Zscaler Inc', 'NASDAQ', 'USD', 'Technology'),
  S('OKTA', 'OKTA', 'Okta Inc', 'NASDAQ', 'USD', 'Technology'),
  S('DDOG', 'DDOG', 'Datadog Inc', 'NASDAQ', 'USD', 'Technology'),
  S('NET', 'NET', 'Cloudflare Inc', 'NASDAQ', 'USD', 'Technology'),
  S('SNOW', 'SNOW', 'Snowflake Inc', 'NASDAQ', 'USD', 'Technology'),
  S('MDB', 'MDB', 'MongoDB Inc', 'NASDAQ', 'USD', 'Technology'),
  S('PLTR', 'PLTR', 'Palantir Technologies', 'NASDAQ', 'USD', 'Technology'),
  S('UBER', 'UBER', 'Uber Technologies', 'NASDAQ', 'USD', 'Technology'),
  S('LYFT', 'LYFT', 'Lyft Inc', 'NASDAQ', 'USD', 'Technology'),
  S('ABNB', 'ABNB', 'Airbnb Inc', 'NASDAQ', 'USD', 'Consumer'),
  S('DASH', 'DASH', 'DoorDash Inc', 'NASDAQ', 'USD', 'Technology'),
  S('RBLX', 'RBLX', 'Roblox Corp', 'NASDAQ', 'USD', 'Technology'),
  S('U', 'U', 'Unity Software', 'NASDAQ', 'USD', 'Technology'),
  S('COIN', 'COIN', 'Coinbase Global', 'NASDAQ', 'USD', 'Finance'),
  S('HOOD', 'HOOD', 'Robinhood Markets', 'NASDAQ', 'USD', 'Finance'),
  S('SOFI', 'SOFI', 'SoFi Technologies', 'NASDAQ', 'USD', 'Finance'),
  S('AFRM', 'AFRM', 'Affirm Holdings', 'NASDAQ', 'USD', 'Finance'),
  S('UPST', 'UPST', 'Upstart Holdings', 'NASDAQ', 'USD', 'Finance'),
  S('XYZ', 'XYZ', 'Block Inc', 'NYSE', 'USD', 'Finance'),
  S('SHOP', 'SHOP', 'Shopify Inc', 'NASDAQ', 'USD', 'Technology'),
  S('ETSY', 'ETSY', 'Etsy Inc', 'NASDAQ', 'USD', 'Consumer'),
  S('EBAY', 'EBAY', 'eBay Inc', 'NASDAQ', 'USD', 'Consumer'),
  S('BIDU', 'BIDU', 'Baidu Inc', 'NASDAQ', 'USD', 'Technology'),
  S('JD', 'JD', 'JD.com Inc', 'NASDAQ', 'USD', 'Consumer'),
  S('PDD', 'PDD', 'PDD Holdings', 'NASDAQ', 'USD', 'Consumer'),
  S('BABA', 'BABA', 'Alibaba Group', 'NASDAQ', 'USD', 'Technology'),
  S('NTES', 'NTES', 'NetEase Inc', 'NASDAQ', 'USD', 'Technology'),
  S('BILI', 'BILI', 'Bilibili Inc', 'NASDAQ', 'USD', 'Technology'),
  S('XPEV', 'XPEV', 'XPeng Inc', 'NASDAQ', 'USD', 'Consumer'),
  S('NIO', 'NIO', 'NIO Inc', 'NASDAQ', 'USD', 'Consumer'),
  S('LI', 'LI', 'Li Auto Inc', 'NASDAQ', 'USD', 'Consumer'),
  S('RIVN', 'RIVN', 'Rivian Automotive', 'NASDAQ', 'USD', 'Consumer'),
  S('LCID', 'LCID', 'Lucid Group', 'NASDAQ', 'USD', 'Consumer'),
  S('ON', 'ON', 'ON Semiconductor', 'NASDAQ', 'USD', 'Technology'),
  S('SMCI', 'SMCI', 'Super Micro Computer', 'NASDAQ', 'USD', 'Technology'),
  S('ARM', 'ARM', 'Arm Holdings', 'NASDAQ', 'USD', 'Technology'),
  S('ASML', 'ASML', 'ASML Holding', 'NASDAQ', 'USD', 'Technology'),
  S('LULU', 'LULU', 'Lululemon Athletica', 'NASDAQ', 'USD', 'Consumer'),
  S('MNST', 'MNST', 'Monster Beverage', 'NASDAQ', 'USD', 'Consumer'),
  S('SBUX', 'SBUX', 'Starbucks Corp', 'NASDAQ', 'USD', 'Consumer'),
  S('TMUS', 'TMUS', 'T-Mobile US', 'NASDAQ', 'USD', 'Technology'),
  S('CHTR', 'CHTR', 'Charter Communications', 'NASDAQ', 'USD', 'Technology'),
  S('CMCSA', 'CMCSA', 'Comcast Corp', 'NASDAQ', 'USD', 'Technology'),
  S('MDLZ', 'MDLZ', 'Mondelez International', 'NASDAQ', 'USD', 'Consumer'),
  S('GILD', 'GILD', 'Gilead Sciences', 'NASDAQ', 'USD', 'Healthcare'),
  S('BIIB', 'BIIB', 'Biogen Inc', 'NASDAQ', 'USD', 'Healthcare'),
  S('REGN', 'REGN', 'Regeneron Pharmaceuticals', 'NASDAQ', 'USD', 'Healthcare'),
  S('VRTX', 'VRTX', 'Vertex Pharmaceuticals', 'NASDAQ', 'USD', 'Healthcare'),
  S('MRNA', 'MRNA', 'Moderna Inc', 'NASDAQ', 'USD', 'Healthcare'),
  S('ILMN', 'ILMN', 'Illumina Inc', 'NASDAQ', 'USD', 'Healthcare'),
  S('IDXX', 'IDXX', 'IDEXX Laboratories', 'NASDAQ', 'USD', 'Healthcare'),
  S('DXCM', 'DXCM', 'DexCom Inc', 'NASDAQ', 'USD', 'Healthcare'),
  S('ISRG', 'ISRG', 'Intuitive Surgical', 'NASDAQ', 'USD', 'Healthcare'),
  S('ZM', 'ZM', 'Zoom Video', 'NASDAQ', 'USD', 'Technology'),
  S('DOCU', 'DOCU', 'DocuSign Inc', 'NASDAQ', 'USD', 'Technology'),
  S('TWLO', 'TWLO', 'Twilio Inc', 'NASDAQ', 'USD', 'Technology'),
  S('HUBS', 'HUBS', 'HubSpot Inc', 'NASDAQ', 'USD', 'Technology'),
  S('TEAM', 'TEAM', 'Atlassian Corp', 'NASDAQ', 'USD', 'Technology'),
  S('WDAY', 'WDAY', 'Workday Inc', 'NASDAQ', 'USD', 'Technology'),
  S('VEEV', 'VEEV', 'Veeva Systems', 'NASDAQ', 'USD', 'Technology'),
  S('PEP', 'PEP', 'PepsiCo Inc', 'NASDAQ', 'USD', 'Consumer'),
  S('SPOT', 'SPOT', 'Spotify Technology', 'NASDAQ', 'USD', 'Technology'),
  // ═══ NYSE (80) ═══
  S('JPM', 'JPM', 'JPMorgan Chase', 'NYSE', 'USD', 'Finance'),
  S('BAC', 'BAC', 'Bank of America', 'NYSE', 'USD', 'Finance'),
  S('GS', 'GS', 'Goldman Sachs', 'NYSE', 'USD', 'Finance'),
  S('MS', 'MS', 'Morgan Stanley', 'NYSE', 'USD', 'Finance'),
  S('WFC', 'WFC', 'Wells Fargo', 'NYSE', 'USD', 'Finance'),
  S('C', 'C', 'Citigroup Inc', 'NYSE', 'USD', 'Finance'),
  S('BLK', 'BLK', 'BlackRock Inc', 'NYSE', 'USD', 'Finance'),
  S('AXP', 'AXP', 'American Express', 'NYSE', 'USD', 'Finance'),
  S('V', 'V', 'Visa Inc', 'NYSE', 'USD', 'Finance'),
  S('MA', 'MA', 'Mastercard Inc', 'NYSE', 'USD', 'Finance'),
  S('BRK-B', 'BRK-B', 'Berkshire Hathaway', 'NYSE', 'USD', 'Finance'),
  S('UNH', 'UNH', 'UnitedHealth Group', 'NYSE', 'USD', 'Healthcare'),
  S('JNJ', 'JNJ', 'Johnson & Johnson', 'NYSE', 'USD', 'Healthcare'),
  S('PFE', 'PFE', 'Pfizer Inc', 'NYSE', 'USD', 'Healthcare'),
  S('MRK', 'MRK', 'Merck & Co', 'NYSE', 'USD', 'Healthcare'),
  S('ABT', 'ABT', 'Abbott Laboratories', 'NYSE', 'USD', 'Healthcare'),
  S('TMO', 'TMO', 'Thermo Fisher Scientific', 'NYSE', 'USD', 'Healthcare'),
  S('DHR', 'DHR', 'Danaher Corp', 'NYSE', 'USD', 'Healthcare'),
  S('LLY', 'LLY', 'Eli Lilly', 'NYSE', 'USD', 'Healthcare'),
  S('BMY', 'BMY', 'Bristol-Myers Squibb', 'NYSE', 'USD', 'Healthcare'),
  S('ABBV', 'ABBV', 'AbbVie Inc', 'NYSE', 'USD', 'Healthcare'),
  S('CVX', 'CVX', 'Chevron Corporation', 'NYSE', 'USD', 'Energy'),
  S('XOM', 'XOM', 'Exxon Mobil', 'NYSE', 'USD', 'Energy'),
  S('COP', 'COP', 'ConocoPhillips', 'NYSE', 'USD', 'Energy'),
  S('SLB', 'SLB', 'Schlumberger Ltd', 'NYSE', 'USD', 'Energy'),
  S('EOG', 'EOG', 'EOG Resources', 'NYSE', 'USD', 'Energy'),
  S('OXY', 'OXY', 'Occidental Petroleum', 'NYSE', 'USD', 'Energy'),
  S('KO', 'KO', 'Coca-Cola Company', 'NYSE', 'USD', 'Consumer'),
  S('PM', 'PM', 'Philip Morris', 'NYSE', 'USD', 'Consumer'),
  S('MO', 'MO', 'Altria Group', 'NYSE', 'USD', 'Consumer'),
  S('WMT', 'WMT', 'Walmart Inc', 'NYSE', 'USD', 'Consumer'),
  S('TGT', 'TGT', 'Target Corp', 'NYSE', 'USD', 'Consumer'),
  S('HD', 'HD', 'Home Depot', 'NYSE', 'USD', 'Consumer'),
  S('LOW', 'LOW', 'Lowes Companies', 'NYSE', 'USD', 'Consumer'),
  S('NKE', 'NKE', 'Nike Inc', 'NYSE', 'USD', 'Consumer'),
  S('DIS', 'DIS', 'Walt Disney Company', 'NYSE', 'USD', 'Consumer'),
  S('T', 'T', 'AT&T Inc', 'NYSE', 'USD', 'Technology'),
  S('VZ', 'VZ', 'Verizon Communications', 'NYSE', 'USD', 'Technology'),
  S('NEE', 'NEE', 'NextEra Energy', 'NYSE', 'USD', 'Energy'),
  S('DUK', 'DUK', 'Duke Energy', 'NYSE', 'USD', 'Energy'),
  S('SO', 'SO', 'Southern Company', 'NYSE', 'USD', 'Energy'),
  S('D', 'D', 'Dominion Energy', 'NYSE', 'USD', 'Energy'),
  S('AEP', 'AEP', 'American Electric Power', 'NYSE', 'USD', 'Energy'),
  S('GE', 'GE', 'GE Aerospace', 'NYSE', 'USD', 'Industrial'),
  S('HON', 'HON', 'Honeywell International', 'NYSE', 'USD', 'Industrial'),
  S('MMM', 'MMM', '3M Company', 'NYSE', 'USD', 'Industrial'),
  S('CAT', 'CAT', 'Caterpillar Inc', 'NYSE', 'USD', 'Industrial'),
  S('DE', 'DE', 'Deere & Company', 'NYSE', 'USD', 'Industrial'),
  S('BA', 'BA', 'Boeing Company', 'NYSE', 'USD', 'Industrial'),
  S('RTX', 'RTX', 'RTX Corporation', 'NYSE', 'USD', 'Industrial'),
  S('LMT', 'LMT', 'Lockheed Martin', 'NYSE', 'USD', 'Industrial'),
  S('NOC', 'NOC', 'Northrop Grumman', 'NYSE', 'USD', 'Industrial'),
  S('GD', 'GD', 'General Dynamics', 'NYSE', 'USD', 'Industrial'),
  S('UPS', 'UPS', 'United Parcel Service', 'NYSE', 'USD', 'Industrial'),
  S('FDX', 'FDX', 'FedEx Corp', 'NYSE', 'USD', 'Industrial'),
  S('F', 'F', 'Ford Motor Company', 'NYSE', 'USD', 'Consumer'),
  S('GM', 'GM', 'General Motors', 'NYSE', 'USD', 'Consumer'),
  S('LIN', 'LIN', 'Linde PLC', 'NYSE', 'USD', 'Materials'),
  S('APD', 'APD', 'Air Products', 'NYSE', 'USD', 'Materials'),
  S('DD', 'DD', 'DuPont de Nemours', 'NYSE', 'USD', 'Materials'),
  S('DOW', 'DOW', 'Dow Inc', 'NYSE', 'USD', 'Materials'),
  S('NEM', 'NEM', 'Newmont Corp', 'NYSE', 'USD', 'Materials'),
  S('FCX', 'FCX', 'Freeport-McMoRan', 'NYSE', 'USD', 'Materials'),
  S('BHP', 'BHP', 'BHP Group', 'NYSE', 'USD', 'Materials'),
  S('RIO', 'RIO', 'Rio Tinto', 'NYSE', 'USD', 'Materials'),
  S('VALE', 'VALE', 'Vale SA', 'NYSE', 'USD', 'Materials'),
  S('CLF', 'CLF', 'Cleveland-Cliffs', 'NYSE', 'USD', 'Materials'),
  S('AA', 'AA', 'Alcoa Corp', 'NYSE', 'USD', 'Materials'),
  S('WPM', 'WPM', 'Wheaton Precious Metals', 'NYSE', 'USD', 'Materials'),
  S('AEM', 'AEM', 'Agnico Eagle Mines', 'NYSE', 'USD', 'Materials'),
  S('PG', 'PG', 'Procter & Gamble', 'NYSE', 'USD', 'Consumer'),
  S('MCD', 'MCD', "McDonald's Corp", 'NYSE', 'USD', 'Consumer'),
  S('ACN', 'ACN', 'Accenture PLC', 'NYSE', 'USD', 'Technology'),
  S('STLA', 'STLA', 'Stellantis NV', 'NYSE', 'USD', 'Consumer'),
  // ═══ CRYPTO (10) ═══
  S('BTC', 'BTC-USD', 'Bitcoin', 'CRYPTO', 'USD', 'Crypto'),
  S('ETH', 'ETH-USD', 'Ethereum', 'CRYPTO', 'USD', 'Crypto'),
  S('BNB', 'BNB-USD', 'Binance Coin', 'CRYPTO', 'USD', 'Crypto'),
  S('SOL', 'SOL-USD', 'Solana', 'CRYPTO', 'USD', 'Crypto'),
  S('XRP', 'XRP-USD', 'Ripple', 'CRYPTO', 'USD', 'Crypto'),
  S('ADA', 'ADA-USD', 'Cardano', 'CRYPTO', 'USD', 'Crypto'),
  S('DOGE', 'DOGE-USD', 'Dogecoin', 'CRYPTO', 'USD', 'Crypto'),
  S('AVAX', 'AVAX-USD', 'Avalanche', 'CRYPTO', 'USD', 'Crypto'),
  S('DOT', 'DOT-USD', 'Polkadot', 'CRYPTO', 'USD', 'Crypto'),
  S('MATIC', 'MATIC-USD', 'Polygon', 'CRYPTO', 'USD', 'Crypto'),
]
